import type { Lang } from "@/lib/i18n";

type LegalSection = {
  title: string;
  body: string;
};

const termsByLang: Record<Lang, readonly LegalSection[]> = {
  sv: [
    { title: "TillÃ¤mpning", body: "Dessa villkor gÃ¤ller fÃ¶r Omega Balance-webbplatsen, kontakt- och partnerformulÃ¤r samt den interna portalen. Vid kÃ¶p, partnerregistrering, ersÃ¤ttning, rank eller placering i extern plattform gÃ¤ller Ã¤ven den plattformens egna villkor och tvingande lokala regler." },
    { title: "Portalens roll", body: "Portalen Ã¤r vÃ¥rt interna arbetslager fÃ¶r trafik, attribution, leads, onboarding och teamstÃ¶d. Den ersÃ¤tter inte nÃ¥gon extern plattforms officiella miljÃ¶ och betyder inte att Omega Balance beslutar om extern struktur, kompensation eller formell partnerstatus." },
    { title: "AnvÃ¤ndning och ansvar", body: "Du mÃ¥ste vara minst 18 Ã¥r och rÃ¤ttsligt behÃ¶rig fÃ¶r att anvÃ¤nda portalen eller gÃ¥ vidare i partnerflÃ¶det. Portalen fÃ¥r bara anvÃ¤ndas fÃ¶r legitim uppfÃ¶ljning, kommunikation och teamarbete. InnehÃ¥llet Ã¤r information och arbetsstÃ¶d, inte juridisk, medicinsk, skattemÃ¤ssig eller finansiell rÃ¥dgivning." },
    { title: "Externa tjÃ¤nster, lokala regler och Ã¤ndringar", body: "Vissa flÃ¶den leder vidare till externa tjÃ¤nster som extern plattform eller vÃ¥ra driftleverantÃ¶rer. Dessa tjÃ¤nster har egna villkor. Tvingande regler i anvÃ¤ndarens land kan ge ytterligare rÃ¤ttigheter som gÃ¤ller fÃ¶re motstridiga avtalsvillkor. Vi kan uppdatera villkoren nÃ¤r verksamhet, lagkrav eller plattform fÃ¶rÃ¤ndras. FrÃ¥gor skickas till hello@insidebalance.eu." },
  ],
  no: [
    { title: "VirkeomrÃ¥de", body: "Disse vilkÃ¥rene gjelder for Omega Balance-nettstedet, kontakt- og partnerskjemaer samt den interne portalen. Ved kjÃ¸p, partnerregistrering, kompensasjon, rang eller plassering i ekstern plattform gjelder ogsÃ¥ plattformens egne vilkÃ¥r og ufravikelige lokale regler." },
    { title: "Portalens rolle", body: "Portalen er vÃ¥rt interne arbeidslag for trafikk, attribusjon, leads, onboarding og teamstÃ¸tte. Den erstatter ikke en ekstern plattforms offisielle miljÃ¸ og betyr ikke at Omega Balance avgjÃ¸r ekstern struktur, kompensasjon eller formell partnerstatus." },
    { title: "Bruk og ansvar", body: "Du mÃ¥ vÃ¦re minst 18 Ã¥r og rettslig kompetent til Ã¥ bruke portalen eller gÃ¥ videre i partnerlÃ¸pet. Portalen skal bare brukes til legitim oppfÃ¸lging, kommunikasjon og teamarbeid. Innholdet er informasjon og arbeidsstÃ¸tte, ikke juridisk, medisinsk, skattemessig eller finansiell rÃ¥dgivning." },
    { title: "Eksterne tjenester, lokale regler og endringer", body: "Noen flyter gÃ¥r videre til eksterne tjenester som ekstern plattform eller vÃ¥re driftsleverandÃ¸rer. Disse tjenestene har egne vilkÃ¥r. Ufravikelige regler i brukerens land kan gi ytterligere rettigheter som gÃ¥r foran motstridende avtaletekst. Vi kan oppdatere vilkÃ¥rene nÃ¥r virksomheten, lovkravene eller plattformen endres. SpÃ¸rsmÃ¥l sendes til hello@insidebalance.eu." },
  ],
  da: [
    { title: "AnvendelsesomrÃ¥de", body: "Disse vilkÃ¥r gÃ¦lder for Omega Balance-websitet, kontakt- og partnerformularer samt den interne portal. Ved kÃ¸b, partnerregistrering, kompensation, rang eller placering i ekstern platform gÃ¦lder ogsÃ¥ platformens egne vilkÃ¥r og ufravigelige lokale regler." },
    { title: "Portalens rolle", body: "Portalen er vores interne arbejdslag for trafik, attribution, leads, onboarding og teamstÃ¸tte. Den erstatter ikke en ekstern platforms officielle miljÃ¸ og betyder ikke, at Omega Balance afgÃ¸r ekstern struktur, kompensation eller formel partnerstatus." },
    { title: "Brug og ansvar", body: "Du skal vÃ¦re mindst 18 Ã¥r og retligt myndig for at bruge portalen eller gÃ¥ videre i partnerforlÃ¸bet. Portalen mÃ¥ kun bruges til legitim opfÃ¸lgning, kommunikation og teamarbejde. Indholdet er information og arbejdsstÃ¸tte, ikke juridisk, medicinsk, skattemÃ¦ssig eller finansiel rÃ¥dgivning." },
    { title: "Eksterne tjenester, lokale regler og Ã¦ndringer", body: "Nogle flows gÃ¥r videre til eksterne tjenester som ekstern platform eller vores driftsleverandÃ¸rer. Disse tjenester har egne vilkÃ¥r. Ufravigelige regler i brugerens land kan give yderligere rettigheder, som gÃ¥r forud for modstridende vilkÃ¥r. Vi kan opdatere vilkÃ¥rene, nÃ¥r forretningen, lovkrav eller platformen Ã¦ndrer sig. SpÃ¸rgsmÃ¥l sendes til hello@insidebalance.eu." },
  ],
  fi: [
    { title: "Soveltamisala", body: "NÃ¤mÃ¤ ehdot koskevat Omega Balance -sivustoa, yhteydenotto- ja partnerilomakkeita sekÃ¤ sisÃ¤istÃ¤ portaalia. Ostoihin, partneriksi liittymiseen, korvauksiin, rankingiin tai sijoitteluun ulkoisessa partneriympÃ¤ristÃ¶ssÃ¤ sovelletaan lisÃ¤ksi kyseisen ympÃ¤ristÃ¶n ehtoja ja pakottavaa paikallista lainsÃ¤Ã¤dÃ¤ntÃ¶Ã¤." },
    { title: "Portaalin rooli", body: "Portaali on sisÃ¤inen tyÃ¶kerroksemme liikenteelle, attribuutiolle, liideille, onboardingille ja tiimituen hallinnalle. Se ei korvaa ulkoisen partneriympÃ¤ristÃ¶n virallista alustaa eikÃ¤ tarkoita, ettÃ¤ Omega Balance pÃ¤Ã¤ttÃ¤isi ulkoisesta rakenteesta, korvauksista tai virallisesta partneristatuksesta." },
    { title: "KÃ¤yttÃ¶ ja vastuu", body: "Sinun tulee olla vÃ¤hintÃ¤Ã¤n 18-vuotias ja oikeudellisesti kelpoinen voidaksesi kÃ¤yttÃ¤Ã¤ portaalia tai edetÃ¤ partneripolulla. Portaalia saa kÃ¤yttÃ¤Ã¤ vain lailliseen seurantaan, viestintÃ¤Ã¤n ja tiimityÃ¶hÃ¶n. SisÃ¤ltÃ¶ on tietoa ja tyÃ¶skentelyn tukea, ei oikeudellista, lÃ¤Ã¤ketieteellistÃ¤, vero- tai talousneuvontaa." },
    { title: "Ulkoiset palvelut, paikalliset sÃ¤Ã¤nnÃ¶t ja muutokset", body: "Osa poluista vie ulkoisiin palveluihin, kuten ulkoiseen partneriympÃ¤ristÃ¶Ã¶n tai palveluntarjoajillemme. NÃ¤illÃ¤ palveluilla on omat ehtonsa. Pakottavat sÃ¤Ã¤nnÃ¶t kÃ¤yttÃ¤jÃ¤n asuinmaassa voivat antaa lisÃ¤oikeuksia, jotka ovat ristiriitaisten sopimusehtojen edellÃ¤. Voimme pÃ¤ivittÃ¤Ã¤ ehtoja, kun toiminta, laki tai alusta muuttuu. Kysymykset voi lÃ¤hettÃ¤Ã¤ osoitteeseen hello@insidebalance.eu." },
  ],
  en: [
    { title: "Scope", body: "These terms apply to the Omega Balance website, contact and partner forms, and the internal portal. Purchases, partner registration, compensation, rank, or placement handled in an external platform are also subject to that platform's own terms and any mandatory local laws that apply in the user's market." },
    { title: "Role of the portal", body: "The portal is our internal layer for traffic, attribution, leads, onboarding, and team support. It does not replace any external platform and must not be read as if Omega Balance decides external structure, compensation, or formal partner status." },
    { title: "Use and responsibility", body: "You must be at least 18 years old and legally capable of using the portal or continuing in the partner flow. The portal may only be used for legitimate follow-up, communication, and team work. Content is provided as information and operational support, not legal, medical, tax, or financial advice." },
    { title: "Third-party services, local rules, and changes", body: "Some journeys continue to external services such as an external platform or our operating providers. Those services have their own terms. Mandatory rules in the user's country may grant additional rights that override conflicting contract wording. We may update these terms when our business, legal obligations, or platform change. Questions can be sent to hello@insidebalance.eu." },
  ],
  de: [
    { title: "Geltungsbereich", body: "Diese Bedingungen gelten fÃ¼r die Omega Balance-Website, Kontakt- und Partnerformulare sowie das interne Portal. FÃ¼r KÃ¤ufe, Partnerregistrierung, VergÃ¼tung, Rang oder Platzierung in einer externen Plattform gelten zusÃ¤tzlich die Bedingungen dieser Plattform und zwingende lokale Vorschriften." },
    { title: "Rolle des Portals", body: "Das Portal ist unsere interne Ebene fÃ¼r Traffic, Attribution, Leads, Onboarding und TeamunterstÃ¼tzung. Es ersetzt keine externe Plattform und bedeutet nicht, dass Omega Balance Ã¼ber externe Struktur, VergÃ¼tung oder formellen Partnerstatus entscheidet." },
    { title: "Nutzung und Verantwortung", body: "Du musst mindestens 18 Jahre alt und rechtlich geschÃ¤ftsfÃ¤hig sein, um das Portal zu nutzen oder im Partnerprozess weiterzugehen. Das Portal darf nur fÃ¼r legitime Nachverfolgung, Kommunikation und Teamarbeit genutzt werden. Die Inhalte dienen als Information und operative UnterstÃ¼tzung, nicht als Rechts-, Medizin-, Steuer- oder Finanzberatung." },
    { title: "Drittanbieter, lokale Regeln und Ã„nderungen", body: "Einige AblÃ¤ufe fÃ¼hren zu externen Diensten wie einer externen Plattform oder unseren Betriebsdienstleistern. Diese Dienste haben eigene Bedingungen. Zwingende Regeln im Land des Nutzers kÃ¶nnen zusÃ¤tzliche Rechte gewÃ¤hren, die widersprechenden Vertragstexten vorgehen. Wir kÃ¶nnen diese Bedingungen anpassen, wenn sich GeschÃ¤ft, Rechtslage oder Plattform Ã¤ndern. Fragen gehen an hello@insidebalance.eu." },
  ],
  fr: [
    { title: "Champ d'application", body: "Ces conditions s'appliquent au site Omega Balance, aux formulaires de contact et de partenariat ainsi qu'au portail interne. Les achats, l'inscription partenaire, la rÃ©munÃ©ration, le rang ou le placement gÃ©rÃ©s dans une plateforme externe restent soumis aux conditions de cette plateforme et aux rÃ¨gles locales impÃ©ratives applicables." },
    { title: "RÃ´le du portail", body: "Le portail constitue notre couche interne pour le trafic, l'attribution, les leads, l'onboarding et le support d'Ã©quipe. Il ne remplace pas une plateforme externe et ne signifie pas qu'Omega Balance dÃ©cide de la structure externe, de la rÃ©munÃ©ration ou du statut partenaire officiel." },
    { title: "Utilisation et responsabilitÃ©", body: "Vous devez avoir au moins 18 ans et la capacitÃ© juridique nÃ©cessaire pour utiliser le portail ou poursuivre dans le parcours partenaire. Le portail ne peut Ãªtre utilisÃ© que pour un suivi lÃ©gitime, la communication et le travail d'Ã©quipe. Le contenu est fourni comme information et appui opÃ©rationnel, non comme conseil juridique, mÃ©dical, fiscal ou financier." },
    { title: "Services tiers, rÃ¨gles locales et modifications", body: "Certains parcours se poursuivent vers des services externes comme une plateforme externe ou nos prestataires techniques. Ces services ont leurs propres conditions. Les rÃ¨gles impÃ©ratives du pays de l'utilisateur peuvent accorder des droits supplÃ©mentaires qui prÃ©valent sur un texte contractuel contraire. Nous pouvons mettre Ã  jour ces conditions lorsque l'activitÃ©, les obligations lÃ©gales ou la plateforme Ã©voluent. Les questions peuvent Ãªtre envoyÃ©es Ã  hello@insidebalance.eu." },
  ],
  it: [
    { title: "Ambito di applicazione", body: "Queste condizioni si applicano al sito Omega Balance, ai moduli di contatto e partnership e al portale interno. Acquisti, registrazione partner, compensi, rank o posizionamento gestiti in una piattaforma esterna restano soggetti anche ai termini di tale piattaforma e alle norme locali imperative applicabili." },
    { title: "Ruolo del portale", body: "Il portale Ã¨ il nostro livello interno per traffico, attribution, lead, onboarding e supporto al team. Non sostituisce una piattaforma esterna e non significa che Omega Balance decida struttura esterna, compensi o status partner formale." },
    { title: "Uso e responsabilitÃ ", body: "Devi avere almeno 18 anni ed essere legalmente capace di usare il portale o proseguire nel percorso partner. Il portale puÃ² essere usato solo per follow-up legittimo, comunicazione e lavoro di team. I contenuti sono forniti come informazione e supporto operativo, non come consulenza legale, medica, fiscale o finanziaria." },
    { title: "Servizi di terzi, regole locali e modifiche", body: "Alcuni flussi proseguono verso servizi esterni come una piattaforma esterna o i nostri fornitori tecnici. Tali servizi hanno propri termini. Le norme imperative del Paese dell'utente possono attribuire diritti ulteriori che prevalgono su clausole contrarie. Possiamo aggiornare queste condizioni quando cambiano attivitÃ , obblighi legali o piattaforma. Per domande scrivi a hello@insidebalance.eu." },
  ],
};

const privacyByLang: Record<Lang, readonly LegalSection[]> = {
  sv: [
    { title: "Personuppgiftsansvarig och kontakt", body: "Tulipa AB (org. nr. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, ansvarar fÃ¶r den behandling som beskrivs hÃ¤r fÃ¶r webbplatsen och portalen. Vid frÃ¥gor om integritet eller om du vill utÃ¶va dina rÃ¤ttigheter kontaktar du hello@insidebalance.eu." },
    { title: "Vilka uppgifter vi behandlar och varfÃ¶r", body: "Vi kan behandla namn, e-postadress, telefonnummer, innehÃ¥ll du skickar i formulÃ¤r, referral-kod, sessionsdata, sidvisningar, CTA-hÃ¤ndelser, attribution, portalstatus och teknisk enhetsinformation. Uppgifterna anvÃ¤nds fÃ¶r att hantera kontakt- och partnerfÃ¶rfrÃ¥gningar, driva portalen, fÃ¶lja upp attribution och onboarding, skydda systemet och fÃ¶rbÃ¤ttra arbetsflÃ¶den." },
    { title: "RÃ¤ttslig grund, mottagare och lagring", body: "RÃ¤ttslig grund Ã¤r normalt avtal eller Ã¥tgÃ¤rder infÃ¶r avtal, berÃ¤ttigat intresse fÃ¶r drift, sÃ¤kerhet och uppfÃ¶ljning samt rÃ¤ttslig fÃ¶rpliktelse dÃ¤r lag krÃ¤ver lagring. Uppgifter kan delas med vÃ¥ra tekniska leverantÃ¶rer nÃ¤r det behÃ¶vs fÃ¶r att driva portalen och hantera dialog, onboarding och uppfÃ¶ljning. Om du vÃ¤ljer att gÃ¥ vidare till en extern plattform via en lÃ¤nk frÃ¥n portalen sker vidare behandling dÃ¤r enligt den plattformens egna villkor och integritetspolicy. Om uppgifter Ã¶verfÃ¶rs utanfÃ¶r EU/EES ska giltig Ã¶verfÃ¶ringsmekanism anvÃ¤ndas. Uppgifter sparas bara sÃ¥ lÃ¤nge de behÃ¶vs fÃ¶r aktiv dialog, portalÃ¥tkomst, onboarding, uppfÃ¶ljning, sÃ¤kerhet och lagkrav." },
    { title: "Cookies, tracking, rÃ¤ttigheter och klagomÃ¥l", body: "Webbplatsen anvÃ¤nder lokal lagring och cookies fÃ¶r att hÃ¥lla ihop referral-lÃ¤nkar, sessioner och nÃ¶dvÃ¤ndig portalfunktion. Vi anvÃ¤nder ocksÃ¥ trafik- och funneldata fÃ¶r att fÃ¶rstÃ¥ vilka sidor och flÃ¶den som fungerar. Om en viss kategori inte anses nÃ¶dvÃ¤ndig enligt lokal ePrivacy- eller cookie-reglering ska den bara anvÃ¤ndas efter giltigt samtycke. Du kan ha rÃ¤tt till tillgÃ¥ng, rÃ¤ttelse, radering, begrÃ¤nsning, dataportabilitet och att invÃ¤nda mot viss behandling enligt GDPR och lokal lag. Du kan ocksÃ¥ klaga till Integritetsskyddsmyndigheten (IMY) eller annan behÃ¶rig tillsynsmyndighet i ditt land." },
  ],
  no: [
    { title: "Behandlingsansvarlig og kontakt", body: "Tulipa AB (org. nr. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, er ansvarlig for behandlingen som beskrives her for nettstedet og portalen. Ved spÃ¸rsmÃ¥l om personvern eller hvis du vil utÃ¸ve rettighetene dine, kontakt hello@insidebalance.eu." },
    { title: "Hvilke opplysninger vi behandler og hvorfor", body: "Vi kan behandle navn, e-postadresse, telefonnummer, innhold du sender i skjemaer, referral-kode, sesjonsdata, sidevisninger, CTA-hendelser, attribusjon, portalstatus og teknisk enhetsinformasjon. Opplysningene brukes til Ã¥ hÃ¥ndtere kontakt- og partnerhenvendelser, drive portalen, fÃ¸lge opp attribusjon og onboarding, beskytte systemet og forbedre arbeidsflyter." },
    { title: "Behandlingsgrunnlag, mottakere og lagring", body: "Behandlingsgrunnlaget er normalt avtale eller tiltak fÃ¸r avtale, berettiget interesse for drift, sikkerhet og oppfÃ¸lging samt rettslig plikt der lov krever lagring. Opplysninger kan deles med vÃ¥re tekniske leverandÃ¸rer nÃ¥r det er nÃ¸dvendig for Ã¥ drive portalen og hÃ¥ndtere dialog, onboarding og oppfÃ¸lging. Hvis du velger Ã¥ gÃ¥ videre til en ekstern plattform via en lenke fra portalen, skjer videre behandling der etter plattformens egne vilkÃ¥r og personvernerklÃ¦ring. Hvis opplysninger overfÃ¸res utenfor EU/EÃ˜S, skal en gyldig overfÃ¸ringsmekanisme brukes. Opplysninger lagres bare sÃ¥ lenge de trengs for aktiv dialog, portaltilgang, onboarding, oppfÃ¸lging, sikkerhet og lovkrav." },
    { title: "Cookies, sporing, rettigheter og klage", body: "Nettstedet bruker lokal lagring og cookies for Ã¥ holde referral-lenker, sesjoner og nÃ¸dvendig portalfunksjon samlet. Vi bruker ogsÃ¥ trafikk- og funneldata for Ã¥ forstÃ¥ hvilke sider og flyter som virker. Hvis en kategori ikke anses nÃ¸dvendig etter lokal ePrivacy- eller cookieregulering, skal den bare brukes etter gyldig samtykke. Du kan ha rett til innsyn, retting, sletting, begrensning, dataportabilitet og Ã¥ protestere mot visse behandlinger etter GDPR og lokal lov. Du kan ogsÃ¥ klage til Datatilsynet eller annen kompetent tilsynsmyndighet i landet ditt." },
  ],
  da: [
    { title: "Dataansvarlig og kontakt", body: "Tulipa AB (org. nr. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, er ansvarlig for den behandling, der beskrives her for websitet og portalen. Ved spÃ¸rgsmÃ¥l om privatliv eller hvis du vil udÃ¸ve dine rettigheder, kontakt hello@insidebalance.eu." },
    { title: "Hvilke oplysninger vi behandler og hvorfor", body: "Vi kan behandle navn, e-mailadresse, telefonnummer, indhold du sender i formularer, referral-kode, sessionsdata, sidevisninger, CTA-hÃ¦ndelser, attribution, portalstatus og teknisk enhedsinformation. Oplysningerne bruges til at hÃ¥ndtere kontakt- og partnerhenvendelser, drive portalen, fÃ¸lge attribution og onboarding, beskytte systemet og forbedre arbejdsgange." },
    { title: "Behandlingsgrundlag, modtagere og lagring", body: "Behandlingsgrundlaget er normalt aftale eller skridt fÃ¸r aftale, legitim interesse i drift, sikkerhed og opfÃ¸lgning samt retlig forpligtelse, hvor loven krÃ¦ver opbevaring. Oplysninger kan deles med vores tekniske leverandÃ¸rer, nÃ¥r det er nÃ¸dvendigt for at drive portalen og hÃ¥ndtere dialog, onboarding og opfÃ¸lgning. Hvis du vÃ¦lger at gÃ¥ videre til en ekstern platform via et link fra portalen, sker den videre behandling der efter platformens egne vilkÃ¥r og privatlivspolitik. Hvis oplysninger overfÃ¸res uden for EU/EÃ˜S, skal gyldig overfÃ¸rselsmekanisme bruges. Oplysninger opbevares kun sÃ¥ lÃ¦nge de er nÃ¸dvendige for aktiv dialog, portaladgang, onboarding, opfÃ¸lgning, sikkerhed og lovkrav." },
    { title: "Cookies, tracking, rettigheder og klage", body: "Websitet bruger lokal lagring og cookies til at holde referral-links, sessioner og nÃ¸dvendig portalfunktion samlet. Vi bruger ogsÃ¥ trafik- og funneldata til at forstÃ¥ hvilke sider og flows der virker. Hvis en kategori ikke anses nÃ¸dvendig efter lokal ePrivacy- eller cookieregulering, mÃ¥ den kun bruges efter gyldigt samtykke. Du kan have ret til indsigt, rettelse, sletning, begrÃ¦nsning, dataportabilitet og at gÃ¸re indsigelse mod visse behandlinger efter GDPR og lokal ret. Du kan ogsÃ¥ klage til Datatilsynet eller en anden kompetent tilsynsmyndighed i dit land." },
  ],
  fi: [
    { title: "RekisterinpitÃ¤jÃ¤ ja yhteystiedot", body: "Tulipa AB (org. nr. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, vastaa tÃ¤ssÃ¤ kuvatusta henkilÃ¶tietojen kÃ¤sittelystÃ¤ sivustolla ja portaalissa. Tietosuojaan liittyvissÃ¤ kysymyksissÃ¤ tai oikeuksien kÃ¤yttÃ¤miseksi voit ottaa yhteyttÃ¤ osoitteeseen hello@insidebalance.eu." },
    { title: "MitÃ¤ tietoja kÃ¤sittelemme ja miksi", body: "Voimme kÃ¤sitellÃ¤ nimeÃ¤, sÃ¤hkÃ¶postiosoitetta, puhelinnumeroa, lomakkeissa annettua sisÃ¤ltÃ¶Ã¤, referral-koodia, sessiotietoja, sivunÃ¤yttÃ¶jÃ¤, CTA-tapahtumia, attribuutiota, portaalistatusta ja teknisiÃ¤ laitetietoja. Tietoja kÃ¤ytetÃ¤Ã¤n yhteydenottojen ja partnerihakemusten kÃ¤sittelyyn, portaalin yllÃ¤pitoon, attribuution ja onboardingin seurantaan, jÃ¤rjestelmÃ¤n suojaamiseen ja tyÃ¶nkulkujen parantamiseen." },
    { title: "KÃ¤sittelyperusteet, vastaanottajat ja sÃ¤ilytys", body: "KÃ¤sittelyperuste on yleensÃ¤ sopimus tai sopimusta edeltÃ¤vÃ¤t toimet, oikeutettu etu toiminnan, turvallisuuden ja seurannan kannalta sekÃ¤ lakisÃ¤Ã¤teinen velvoite, jos laki edellyttÃ¤Ã¤ sÃ¤ilytystÃ¤. Tietoja voidaan jakaa teknisille palveluntarjoajillemme silloin, kun se on tarpeen portaalin yllÃ¤pitÃ¤miseksi sekÃ¤ yhteydenpidon, onboardingin ja seurannan hoitamiseksi. Jos pÃ¤Ã¤tÃ¤t siirtyÃ¤ ulkoiseen partneriympÃ¤ristÃ¶Ã¶n portaalin linkin kautta, jatkokÃ¤sittely tapahtuu siellÃ¤ kyseisen ympÃ¤ristÃ¶n omien ehtojen ja tietosuojakÃ¤ytÃ¤nnÃ¶n mukaisesti. Jos tietoja siirretÃ¤Ã¤n EU:n tai ETA:n ulkopuolelle, kÃ¤ytÃ¶ssÃ¤ tulee olla laillinen siirtomekanismi. Tietoja sÃ¤ilytetÃ¤Ã¤n vain niin kauan kuin niitÃ¤ tarvitaan aktiiviseen yhteydenpitoon, portaalin kÃ¤yttÃ¶Ã¶n, onboardingiin, seurantaan, turvallisuuteen ja lakisÃ¤Ã¤teisiin velvoitteisiin." },
    { title: "EvÃ¤steet, seuranta, oikeudet ja valitus", body: "Sivusto kÃ¤yttÃ¤Ã¤ paikallista tallennusta ja evÃ¤steitÃ¤ referral-linkkien, sessioiden ja vÃ¤lttÃ¤mÃ¤ttÃ¶mÃ¤n portaalitoiminnan yllÃ¤pitÃ¤miseen. KÃ¤ytÃ¤mme myÃ¶s liikenne- ja funneldataa ymmÃ¤rtÃ¤Ã¤ksemme, mitkÃ¤ sivut ja polut toimivat. Jos jokin kategoria ei ole vÃ¤lttÃ¤mÃ¤tÃ¶n paikallisen ePrivacy- tai evÃ¤stesÃ¤Ã¤ntelyn mukaan, sitÃ¤ saa kÃ¤yttÃ¤Ã¤ vain pÃ¤tevÃ¤n suostumuksen jÃ¤lkeen. Sinulla voi olla oikeus saada pÃ¤Ã¤sy tietoihin, oikaista niitÃ¤, pyytÃ¤Ã¤ poistamista, rajoittaa kÃ¤sittelyÃ¤, saada tiedot siirrettyÃ¤ ja vastustaa tiettyÃ¤ kÃ¤sittelyÃ¤ GDPR:n ja paikallisen lain mukaisesti. Voit myÃ¶s tehdÃ¤ valituksen tietosuojavaltuutetun toimistolle tai muulle toimivaltaiselle viranomaiselle maassasi." },
  ],
  en: [
    { title: "Controller and contact", body: "Tulipa AB (org. no. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, is responsible for the processing described here for the website and portal. If you have privacy questions or want to exercise your rights, contact hello@insidebalance.eu." },
    { title: "What data we process and why", body: "We may process your name, email address, phone number, content submitted in forms, referral code, session data, page views, CTA events, attribution data, portal status, and technical device information. This is used to handle contact and partner enquiries, operate the portal, follow attribution and onboarding, protect the service, and improve workflows." },
    { title: "Legal bases, recipients, and retention", body: "The main legal bases are contract or steps prior to contract, legitimate interests in operating and securing the service, and legal obligations where records must be retained. Data may be shared with our technical providers where needed to run the portal and handle dialogue, onboarding, and follow-up. If you choose to continue to an external platform through a link from the portal, further processing takes place there under that platform's own terms and privacy policy. If data is transferred outside the EU or EEA, an appropriate transfer mechanism should apply. Data is kept only as long as needed for active dialogue, portal access, onboarding, follow-up, security, and legal requirements." },
    { title: "Cookies, tracking, rights, and complaints", body: "The website uses local storage and cookies to keep referral links, sessions, and necessary portal functions working. We also use traffic and funnel data to understand which pages and journeys perform. If a category is not considered necessary under applicable ePrivacy or cookie rules, it should only be used after valid consent. Depending on your jurisdiction, you may have rights to access, rectification, erasure, restriction, portability, and objection under the GDPR and local law. You may also lodge a complaint with your local supervisory authority." },
  ],
  de: [
    { title: "Verantwortlicher und Kontakt", body: "Tulipa AB (org. nr. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, ist fÃ¼r die hier beschriebene Verarbeitung auf Website und Portal verantwortlich. Bei Fragen zum Datenschutz oder zur AusÃ¼bung deiner Rechte kontaktiere bitte hello@insidebalance.eu." },
    { title: "Welche Daten wir verarbeiten und warum", body: "Wir kÃ¶nnen Namen, E-Mail-Adresse, Telefonnummer, Formularinhalte, Referral-Code, Sitzungsdaten, Seitenaufrufe, CTA-Ereignisse, Attributionsdaten, Portalstatus und technische GerÃ¤teinformationen verarbeiten. Dies dient der Bearbeitung von Kontakt- und Partneranfragen, dem Betrieb des Portals, der Nachverfolgung von Attribution und Onboarding, dem Schutz des Dienstes und der Verbesserung von ArbeitsablÃ¤ufen." },
    { title: "Rechtsgrundlagen, EmpfÃ¤nger und Speicherdauer", body: "Rechtsgrundlagen sind in der Regel Vertrag oder vorvertragliche MaÃŸnahmen, berechtigte Interessen an Betrieb und Sicherheit sowie gesetzliche Pflichten, soweit Daten aufbewahrt werden mÃ¼ssen. Daten kÃ¶nnen an technische Dienstleister weitergegeben werden, soweit dies fÃ¼r den Betrieb des Portals sowie fÃ¼r Dialog, Onboarding und Nachverfolgung erforderlich ist. Wenn du dich entscheidest, Ã¼ber einen Link aus dem Portal zu einer externen Plattform weiterzugehen, findet die weitere Verarbeitung dort nach den Bedingungen und Datenschutzhinweisen dieser Plattform statt. Bei Ãœbermittlungen auÃŸerhalb der EU oder des EWR muss ein zulÃ¤ssiger Ãœbermittlungsmechanismus gelten. Daten werden nur so lange gespeichert, wie sie fÃ¼r aktiven Dialog, Portalzugang, Onboarding, Nachverfolgung, Sicherheit und gesetzliche Anforderungen benÃ¶tigt werden." },
    { title: "Cookies, Tracking, Rechte und Beschwerden", body: "Die Website nutzt lokale Speicherung und Cookies, um Referral-Links, Sitzungen und notwendige Portalfunktionen zusammenzuhalten. ZusÃ¤tzlich verwenden wir Traffic- und Funnel-Daten, um zu verstehen, welche Seiten und AblÃ¤ufe funktionieren. Wenn eine Kategorie nach anwendbarem ePrivacy- oder Cookie-Recht nicht als notwendig gilt, darf sie nur nach wirksamer Einwilligung verwendet werden. Je nach ZustÃ¤ndigkeit kannst du Rechte auf Auskunft, Berichtigung, LÃ¶schung, EinschrÃ¤nkung, DatenÃ¼bertragbarkeit und Widerspruch nach DSGVO und lokalem Recht haben. AuÃŸerdem kannst du dich an die zustÃ¤ndige DatenschutzaufsichtsbehÃ¶rde wenden." },
  ],
  fr: [
    { title: "Responsable du traitement et contact", body: "Tulipa AB (org. no. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, est responsable du traitement dÃ©crit ici pour le site et le portail. Pour toute question relative Ã  la protection des donnÃ©es ou pour exercer vos droits, contactez hello@insidebalance.eu." },
    { title: "Quelles donnÃ©es nous traitons et pourquoi", body: "Nous pouvons traiter votre nom, votre adresse e-mail, votre numÃ©ro de tÃ©lÃ©phone, le contenu envoyÃ© dans les formulaires, le code de recommandation, les donnÃ©es de session, les pages vues, les Ã©vÃ©nements CTA, les donnÃ©es d'attribution, le statut portail et des informations techniques sur l'appareil. Ces donnÃ©es servent Ã  gÃ©rer les demandes de contact et de partenariat, faire fonctionner le portail, suivre l'attribution et l'onboarding, protÃ©ger le service et amÃ©liorer les flux de travail." },
    { title: "Bases juridiques, destinataires et conservation", body: "Les bases juridiques principales sont le contrat ou les mesures prÃ©contractuelles, l'intÃ©rÃªt lÃ©gitime pour exploiter et sÃ©curiser le service, ainsi que les obligations lÃ©gales lorsque des donnÃ©es doivent Ãªtre conservÃ©es. Les donnÃ©es peuvent Ãªtre partagÃ©es avec nos prestataires techniques lorsque cela est nÃ©cessaire pour faire fonctionner le portail et gÃ©rer le dialogue, l'onboarding et le suivi. Si vous choisissez de poursuivre vers une plateforme externe via un lien du portail, le traitement ultÃ©rieur a lieu lÃ -bas selon les conditions et la politique de confidentialitÃ© de cette plateforme. En cas de transfert hors UE ou EEE, un mÃ©canisme valable doit s'appliquer. Les donnÃ©es ne sont conservÃ©es que le temps nÃ©cessaire au dialogue actif, Ã  l'accÃ¨s au portail, Ã  l'onboarding, au suivi, Ã  la sÃ©curitÃ© et aux obligations lÃ©gales." },
    { title: "Cookies, tracking, droits et rÃ©clamations", body: "Le site utilise le stockage local et des cookies pour maintenir le fonctionnement des liens de recommandation, des sessions et des fonctions nÃ©cessaires du portail. Nous utilisons aussi des donnÃ©es de trafic et de funnel pour comprendre quelles pages et quels parcours fonctionnent. Si une catÃ©gorie n'est pas considÃ©rÃ©e comme nÃ©cessaire au regard des rÃ¨gles applicables ePrivacy ou cookies, elle ne doit Ãªtre utilisÃ©e qu'aprÃ¨s un consentement valable. Selon votre situation, vous pouvez disposer de droits d'accÃ¨s, de rectification, d'effacement, de limitation, de portabilitÃ© et d'opposition au titre du RGPD et du droit local. Vous pouvez Ã©galement dÃ©poser une rÃ©clamation auprÃ¨s de la CNIL ou d'une autre autoritÃ© compÃ©tente." },
  ],
  it: [
    { title: "Titolare del trattamento e contatto", body: "Tulipa AB (org. no. 556803-6817), Nya SÃ¶rÃ¥kersgatan 5, 861 51 SÃ¶rÃ¥ker, Ã¨ responsabile del trattamento descritto qui per il sito e il portale. Per domande sulla privacy o per esercitare i tuoi diritti puoi contattare hello@insidebalance.eu." },
    { title: "Quali dati trattiamo e perchÃ©", body: "Possiamo trattare nome, indirizzo e-mail, numero di telefono, contenuti inviati nei moduli, codice referral, dati di sessione, pagine viste, eventi CTA, dati di attribution, stato del portale e informazioni tecniche sul dispositivo. Questi dati servono a gestire richieste di contatto e partnership, far funzionare il portale, seguire attribution e onboarding, proteggere il servizio e migliorare i flussi di lavoro." },
    { title: "Basi giuridiche, destinatari e conservazione", body: "Le principali basi giuridiche sono il contratto o misure precontrattuali, l'interesse legittimo a gestire e proteggere il servizio e gli obblighi legali quando alcuni dati devono essere conservati. I dati possono essere condivisi con fornitori tecnici quando necessario per far funzionare il portale e gestire dialogo, onboarding e follow-up. Se scegli di proseguire verso una piattaforma esterna tramite un link del portale, l'ulteriore trattamento avviene lÃ¬ secondo i termini e l'informativa privacy di quella piattaforma. Se i dati sono trasferiti fuori dall'UE o dallo SEE, deve applicarsi un meccanismo di trasferimento valido. I dati sono conservati solo per il tempo necessario al dialogo attivo, all'accesso al portale, all'onboarding, al follow-up, alla sicurezza e agli obblighi legali." },
    { title: "Cookie, tracking, diritti e reclami", body: "Il sito utilizza memorizzazione locale e cookie per mantenere funzionanti link referral, sessioni e funzioni necessarie del portale. Utilizziamo anche dati di traffico e funnel per capire quali pagine e percorsi funzionano. Se una categoria non Ã¨ considerata necessaria ai sensi delle regole applicabili su ePrivacy o cookie, deve essere usata solo dopo consenso valido. A seconda della giurisdizione, puoi avere diritti di accesso, rettifica, cancellazione, limitazione, portabilitÃ  e opposizione ai sensi del GDPR e della legge locale. Puoi anche presentare reclamo al Garante o ad altra autoritÃ  competente." },
  ],
};

const noticePointsByLang: Record<Lang, readonly string[]> = {
  sv: ["Du mÃ¥ste vara minst 18 Ã¥r och myndig fÃ¶r att fÃ¥ tillgÃ¥ng till portalen.", "Portalen Ã¤r vÃ¥rt interna teamlager och inte nÃ¥gon extern plattforms officiella miljÃ¶.", "Extern partnerplattform ansvarar fÃ¶r officiell struktur, rank, placering, kvalificering och kompensation.", "Omega Balance ansvarar fÃ¶r vÃ¥rt arbetslager kring trafik, attribution, leads, onboarding och teamstÃ¶d."],
  no: ["Du mÃ¥ vÃ¦re minst 18 Ã¥r og myndig for Ã¥ fÃ¥ tilgang til portalen.", "Portalen er vÃ¥rt interne teamlag og ikke en ekstern plattforms offisielle miljÃ¸.", "Ekstern partnerplattform har ansvar for offisiell struktur, rang, plassering, kvalifisering og kompensasjon.", "Omega Balance har ansvar for vÃ¥rt arbeidslag rundt trafikk, attribusjon, leads, onboarding og teamstÃ¸tte."],
  da: ["Du skal vÃ¦re mindst 18 Ã¥r og myndig for at fÃ¥ adgang til portalen.", "Portalen er vores interne teamlag og ikke en ekstern platforms officielle miljÃ¸.", "Ekstern partnerplatform har ansvar for officiel struktur, rang, placering, kvalificering og kompensation.", "Omega Balance har ansvar for vores arbejdslag omkring trafik, attribution, leads, onboarding og teamstÃ¸tte."],
  fi: ["Sinun tulee olla vÃ¤hintÃ¤Ã¤n 18-vuotias ja tÃ¤ysivaltainen saadaksesi pÃ¤Ã¤syn portaaliin.", "Portaali on sisÃ¤inen tiimikerroksemme eikÃ¤ ulkoisen partneriympÃ¤ristÃ¶n virallinen alusta.", "Ulkoinen partneriympÃ¤ristÃ¶ vastaa virallisesta rakenteesta, rankingista, sijoittelusta, kvalifioinnista ja korvauksista.", "Omega Balance vastaa omasta tyÃ¶kerroksestamme liikenteen, attribuution, liidien, onboardingin ja tiimituen osalta."],
  en: ["You must be at least 18 years old and legally competent to access the portal.", "The portal is our internal team layer and not an external platform's official environment.", "The external platform remains responsible for official structure, rank, placement, qualification, and compensation.", "Omega Balance is responsible for our operational layer around traffic, attribution, leads, onboarding, and team support."],
  de: ["Du musst mindestens 18 Jahre alt und geschÃ¤ftsfÃ¤hig sein, um Zugang zum Portal zu erhalten.", "Das Portal ist unsere interne Team-Ebene und nicht die offizielle Umgebung einer externen Plattform.", "Die externe Plattform bleibt fÃ¼r offizielle Struktur, Rang, Platzierung, Qualifikation und VergÃ¼tung verantwortlich.", "Omega Balance verantwortet unsere operative Ebene fÃ¼r Traffic, Attribution, Leads, Onboarding und TeamunterstÃ¼tzung."],
  fr: ["Vous devez avoir au moins 18 ans et la capacitÃ© juridique nÃ©cessaire pour accÃ©der au portail.", "Le portail constitue notre couche interne d'Ã©quipe et non l'environnement officiel d'une plateforme externe.", "La plateforme externe reste responsable de la structure officielle, du rang, du placement, de la qualification et de la rÃ©munÃ©ration.", "Omega Balance est responsable de notre couche opÃ©rationnelle concernant le trafic, l'attribution, les leads, l'onboarding et le support d'Ã©quipe."],
  it: ["Devi avere almeno 18 anni ed essere legalmente capace di accedere al portale.", "Il portale Ã¨ il nostro livello interno di team e non l'ambiente ufficiale di una piattaforma esterna.", "La piattaforma esterna resta responsabile di struttura ufficiale, rank, posizionamento, qualificazione e compensi.", "Omega Balance Ã¨ responsabile del nostro livello operativo per traffico, attribution, lead, onboarding e supporto al team."],
};

export function getPortalTermsSections(lang: Lang) {
  return termsByLang[lang] || termsByLang.sv;
}

export function getPortalPrivacySections(lang: Lang) {
  return privacyByLang[lang] || privacyByLang.sv;
}

export function getPortalNoticePoints(lang: Lang) {
  return noticePointsByLang[lang] || noticePointsByLang.sv;
}

export const portalTermsSections = termsByLang.sv;
export const portalPrivacySections = privacyByLang.sv;
export const portalNoticePoints = noticePointsByLang.sv;

